# Multi-service Docker Compose for development and testing
version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - '3000:8080'
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    networks:
      - naubion-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - '8080:8080'
    environment:
      - NODE_ENV=production
      - PORT=8080
      - DATABASE_URL=${DATABASE_URL}
      - MAILJET_API_KEY=${MAILJET_API_KEY}
      - MAILJET_SECRET_KEY=${MAILJET_SECRET_KEY}
    depends_on:
      - postgres
    networks:
      - naubion-network
    volumes:
      - backend-data:/app/data

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=naubion
      - POSTGRES_USER=naubion
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - naubion-network

  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    networks:
      - naubion-network

volumes:
  postgres-data:
  redis-data:
  backend-data:

networks:
  naubion-network:
    driver: bridge
